# Generated by Django 2.2 on 2021-04-02 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='register_blog',
            fields=[
                ('register_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SECONDAPPLICATION.register')),
                ('BlogName', models.CharField(max_length=40)),
            ],
            bases=('SECONDAPPLICATION.register',),
        ),
    ]
