# Generated by Django 2.2 on 2021-04-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0005_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
