# Generated by Django 2.2 on 2021-04-03 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='user_password',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=datetime.datetime(2021, 4, 3, 19, 57, 20, 392684, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 4, 3, 19, 57, 34, 132446, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
