# Generated by Django 2.2 on 2021-04-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_auto_20210403_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
