# Generated by Django 2.2 on 2021-04-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0005_auto_20210403_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsistration',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
