# Generated by Django 2.2 on 2021-04-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_auto_20210403_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='regsistration',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
