# Generated by Django 2.2 on 2021-04-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0007_auto_20210404_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsistration',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
