# Generated by Django 2.2 on 2021-04-04 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0008_auto_20210404_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='regsistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='regsistration',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
