# Generated by Django 2.2 on 2021-04-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0009_auto_20210404_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLogRegsistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True)),
            ],
        ),
    ]
